---

- name: Import docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ back_end_directory }}/docker-compose.yml"
    owner: "{{ back_end_user }}"
    group: "{{ back_end_group }}"
  notify: Restart docker compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ back_end_directory }}"